export const EMPTY_WORKER_TYPE = 'EMPTY_WORKER_TYPE';
export const SPAWNER_WORKER_TYPE = 'SPAWNER_WORKER_TYPE';
export const PLAYER_WORKER_TYPE = 'PLAYER_WORKER_TYPE';
export const ENEMY_WORKER_TYPE = 'ENEMY_WORKER_TYPE';
export const BULLET_WORKER_TYPE = 'BULLET_WORKER_TYPE';
export const BONUS_WORKER_TYPE = 'BONUS_WORKER_TYPE';
